global:
  smtp_smarthost: 'smtp.gmail.com:587'   # Adresse du serveur SMTP
  smtp_from: ${SMTP_FROM}  # Adresse de l'expéditeur
  smtp_auth_username: ${SMTP_AUTH_USERNAME}  # Nom d'utilisateur SMTP
  smtp_auth_password: ${SMTP_AUTH_PASSWORD}        # Mot de passe SMTP
  smtp_require_tls: true                          # Activer TLS pour la sécurité

route:
  group_by: ['alertname']
  group_wait: 5s
  group_interval: 5m
  repeat_interval: 4h
  receiver: "default-email"
receivers:
  - name: "default-email"
    email_configs:
      - to: ${ALERT_EMAIL_RECEIVER}              # Destinataire
        send_resolved: true                    # Envoyer aussi les alertes résolues
