global:
  scrape_interval: 15s
  scrape_timeout: 15s
  evaluation_interval: 1m
  query_log_file: querylogs
  scrape_failure_log_file: queryerrors

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'django_backend'
    scheme: https
    metrics_path: '/api/metrics'
    tls_config:
      ca_file: '/etc/prometheus/certs/ca.crt'
      # cert_file: "/etc/prometheus/certs/nginx.crt"
      # key_file: "/etc/prometheus/certs/nginx.key"
      insecure_skip_verify: true
    static_configs:
      - targets: ['host.docker.internal']
  - job_name: 'nginx_metrics'
    metrics_path: '/metrics'
    # tls_config:
    #   ca_file: '/etc/prometheus/certs/ca.crt'
      # cert_file: "/etc/prometheus/certs/nginx.crt"
      # key_file: "/etc/prometheus/certs/nginx.key"
      # insecure_skip_verify: true
    static_configs:
      - targets: ['nginx_exporter:9913']

