global:
  scrape_interval: 15s
  scrape_timeout: 15s
  evaluation_interval: 30s
  query_log_file: querylogs
  scrape_failure_log_file: queryerrors

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'django_backend'
    scheme: https
    metrics_path: '/api/metrics'
    cert_file:
    key_file:
    static_configs:
      - targets: ['localhost']
# tls_server_config:
#   cert_file: /etc/certs/prometheus.crt
#   key_file: /etc/certs/prometheus.key
#   client_auth_type: "RequireAndVerifyClientCert"
#   client_ca_file: /etc/certs/ca.crt
